version: "3.9"

services:

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped
    networks:
      - logspot-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    restart: unless-stopped
    networks:
      - logspot-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # Connessione al vostro MongoDB Atlas in Cloud
      SPRING_DATA_MONGODB_URI: mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/?retryWrites=true&w=majority
      # Stringa di Azure Service Bus
      AZURE_SERVICEBUS_CONNECTION_STRING: ${AZURE_SERVICEBUS_CONNECTION_STRING}
    restart: unless-stopped
    networks:
      - logspot-network

  catalog-service:
    build:
      context: ./catalog-service
    container_name: catalog-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/?retryWrites=true&w=majority
    restart: unless-stopped
    networks:
      - logspot-network

  therapy-service:
    build:
      context: ./therapy-service
    container_name: therapy-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/?retryWrites=true&w=majority
      AZURE_SERVICEBUS_CONNECTION_STRING: ${AZURE_SERVICEBUS_CONNECTION_STRING}
    restart: unless-stopped
    networks:
      - logspot-network

  logspot-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logspot_web_local
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      # Il frontend non usa più Mongoose, ma manteniamo la variabile nel caso serva a vecchi script
      MONGODB_URI: mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/?retryWrites=true&w=majority
      # Indirizzo del Gateway interno alla rete Docker per le API (Fondamentale)
      GATEWAY_URL: http://gateway-service:8080
    depends_on:
      - gateway-service
    restart: unless-stopped
    networks:
      - logspot-network

networks:
  logspot-network:
    driver: bridge