spring.application.name=service-terapia
spring.config.import=optional:configserver:
therapy.mongodb.uri=mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/test?retryWrites=true&w=majority
therapy.mongodb.database=test
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server.port=8083

# Configurazione base per Eureka Client
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.preferIpAddress=true

# Azure Service Bus
azure.servicebus.connection-string=${AZURE_SERVICEBUS_CONNECTION_STRING}
