spring.application.name=service-user

spring.config.import=optional:configserver:

user.mongodb.uri=mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/test?retryWrites=true&w=majority
user.mongodb.database=test

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.preferIpAddress=true

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=3600000