spring.application.name=service-user

spring.config.import=optional:configserver:

user.mongodb.uri=mongodb+srv://Tomm:pinopino@cluster0.cymdcty.mongodb.net/test?retryWrites=true&w=majority
user.mongodb.database=test



server.port=8081

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.preferIpAddress=true

# Azure Service Bus
spring.cloud.azure.servicebus.connection-string=${AZURE_SERVICEBUS_CONNECTION_STRING}
spring.jms.servicebus.pricing-tier=standard

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=3600000